UK-Export-Finance/tfs-api

- .eslintrc.json
- .husky/commit-msg
- jest.config.ts
- src/constants/application.ts
- src/constants/index.ts
- tsconfig.json
Centralised micro-service constants
* Jest, TS and ESLint config have been updated with alias `@ukef/constants`.
* Added `APPLICATION` constant.
* `.husky` pre-comment script executes `npm run lint`.
> feat(API-97): Centralised constants introduction

- src/modules/acbs/acbs-authentication.service.test.ts
- src/modules/acbs/acbs-party-external-rating.service.test.ts
- src/modules/acbs/acbs-party-external-rating.service.ts
- src/modules/acbs/acbs-party.service.test.ts
- src/modules/acbs/acbs-party.service.ts
- src/modules/acbs/acbs.module.ts
- src/modules/acbs/dto/acbs-get-party-response.dto.ts
- src/modules/acbs/wrap-acbs-http-error.ts
- src/modules/party-external-rating/party-external-rating.controller.test.ts
- src/modules/party-external-rating/party-external-rating.service.test.ts
- src/modules/party-external-rating/party-external-rating.service.ts
- src/modules/party/dto/get-party-by-response.dto.ts
- src/modules/party/party.controller.test.ts
- src/modules/party/party.controller.ts
- src/modules/party/party.interface.ts
- src/modules/party/party.service.get-party-by-identifier.test.ts
- src/modules/party/party.service.test.ts
- src/modules/party/party.service.ts
- src/modules/tfs.module.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/docs/get-docs-yaml.api-test.ts
- test/party-external-rating/get-party-external-ratings.api-test.ts
- test/party/get-party-by-party-identifier.api-test.ts
- test/support/api.ts
- test/support/generator/abstract-generator.ts
- test/support/generator/party-external-rating-generator.ts
- test/support/generator/party-generator.ts
`GET /parties/{partyIdentifier}` needs to get the party with the given identifier from ACBS
- I've added the new endpoint, `GET /parties/{partyIdentifier}`, to get an authentication token from ACBS and then get the party from ACBS
- if ACBS returns a 200 response, then we transform and return the party
- if ACBS returns a 400 response with a message containing "Party not found" then we return a 404
- if ACBS returns an unexpected error or times out, then we return a 500
- there's no validation on the `partyIdentifier` URL param
- I've also added a snapshot test for the swagger yaml we're generating from our decorators, so that we can double-check any changes we make to this
- There is some overlap with APIM-79 which isn't merged yet
> feat(APIM-78): add endpoint to get party by party identifier

- .env.sample
- .eslintrc.json
- src/modules/auth/strategy/api-key.strategy.test.ts
We want to merge https://github.com/UK-Export-Finance/tfs-api/pull/21 but we have one final comment to address: unit testing the ApiKeyStrategy.
Note that I can't update that review directly as I don't have permission to push to the repo.
I've added a unit test file for the ApiKeyStrategy. I found the best way to test this was to mimic how passport will use it by calling the authenticate method and checking the correct callback is triggered. This does mean we're testing a bit of 3rd party logic from `passport-headerapikey` which provides the base class we inherit from, but I think this is worth it in this case to get a more meaningful test
> feat: added unit tests for ApiKeyStrategy

- src/swagger.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
Since we added global authentication to TFS, all requests sent from the Swagger UI will fail authentication because they will not include the API Key header
The fix is to document the security scheme in the swagger specification and document that it is applied globally. This improves our documentation and also allow you to set the value of the header when using Swagger UI
> feat: add global auth definition to swagger

- src/constants/acbs.constant.ts
- src/constants/application.constant.ts
- src/constants/properties.constant.ts
In PR 29, we raised that we should make the exports consistent in our constant files (see the conversation [here](https://github.com/UK-Export-Finance/tfs-api/pull/29#discussion_r1147178859))
I've changed all constant files to
```
export const <constant name> = { ... };
```
instead of 
```
const <constant name> = { ... };
export { const };
```
> refactor: make export consistent in constant files

- src/constants/date-formats.constant.ts
- src/constants/index.ts
- src/decorators/validated-date-only-api-property.decorator.ts
- src/modules/date/date-string.transformations.test.ts
- src/modules/date/date-string.transformations.ts
- src/modules/date/date.module.ts
- src/modules/deal-guarantee/deal-guarantee.controller.test.ts
- src/modules/deal-guarantee/deal-guarantee.service.test.ts
- src/modules/deal-guarantee/deal-guarantee.service.ts
- src/modules/party/party.controller.test.ts
- src/modules/party/party.module.ts
- src/modules/party/party.service.get-party-by-identifier.test.ts
- src/modules/party/party.service.test.ts
- src/modules/party/party.service.ts
- test/deal-guarantee/post-deal-guarantee.api-test.ts
- test/support/generator/party-generator.ts
- test/support/generator/random-value-generator.ts
In a few different places in the code, we do the same date string conversions:
- removing the time part of a date time string
- adding the time part to a date only string
We should commonise this logic
@avaitonis had already done some of this work in [his open PR](https://github.com/UK-Export-Finance/tfs-api/pull/28) where he added a `DateStringTransformations` class. I've:
- moved it to the DateModule, so it can be dependency injected into other modules
- added some unit tests
- added a new method for adding the time part  to a date only string
- used the class in existing code
> refactor: commonise date string conversions

- src/modules/acbs/acbs-deal-guarantee.service.test.ts
- src/modules/acbs/acbs-deal-guarantee.service.ts
- src/modules/acbs/acbs-deal.service.test.ts
- src/modules/acbs/acbs-deal.service.ts
- src/modules/acbs/acbs-facility-party.service.test.ts
- src/modules/acbs/acbs-facility-party.service.ts
- src/modules/acbs/acbs.module.ts
- src/modules/acbs/dto/acbs-create-deal.dto.ts
- src/modules/acbs/wrap-acbs-http-error-callback.ts
- test/support/generator/random-value-generator.ts
- test/support/requests/acbs-create-deal-dto.ts
- test/support/requests/acbs-create-deal-guarantee-dto.ts
- test/support/requests/acbs-create-facility-party-dto.ts
As part of APIM-74 (migrating the `POST /deals` endpoint), we want to create an ACBS service that can create deals in ACBS.
Note that this is only part of APIM-74, a later PR will complete the ticket.
I've created an AcbsDealService with unit tests. This will POST a request body to ACBS. If ACBS returns a 400 error then the service with throw an `AcbsBadRequestException`, if ACBS returns a non-400 error then the service will throw an `AcbsUnexpectedException`.
This is a bit different from the existing ACBS POST calls which can also throw an `AcbsResourceNotFoundException` if ACBS returns a 400 error with a known string message (like 'Deal not found'). To make that clear, I've refactored how we handle POST errors so that the code states specifically _which_ POST calls expect _which_ error …
> feat(APIM-74): add acbs service to create deals

- src/constants/properties.constant.ts
- src/decorators/validated-date-only-api-property.decorator.ts
- src/decorators/validated-string-api-property.decorator.ts
- src/modules/acbs/acbs-deal-party.service.test.ts
- src/modules/acbs/acbs-deal-party.service.ts
- src/modules/acbs/dto/acbs-create-deal-investor-request.dto.ts
- src/modules/date/date-string.transformations.ts
- src/modules/deal-investor/deal-investor.controller.test.ts
- src/modules/deal-investor/deal-investor.controller.ts
- src/modules/deal-investor/deal-investor.service.create-investor.test.ts
- src/modules/deal-investor/deal-investor.service.get-investors.test.ts
- src/modules/deal-investor/deal-investor.service.ts
- src/modules/deal-investor/dto/create-deal-investor-request.dto.ts
- src/modules/deal-investor/dto/create-deal-investor-response.dto.ts
- src/modules/deal-investor/dto/deal-investor-response.dto.ts
- test/common-tests/request-field-validation-api-tests/date-only-field-validation-api-tests.ts
- test/common-tests/request-field-validation-api-tests/string-field-validation-api-tests.ts
- test/deal-guarantee/post-deal-guarantee.api-test.ts
- test/deal-investor/get-deal-investors-by-deal-identifier.api-test.ts
- test/deal-investor/post-deal-investors.api-test.ts
- test/deal/post-deal.api-test.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/facility-investor/post-facility-investor.api-test.ts
- test/support/generator/create-deal-investor-generator.ts
- test/support/generator/get-deal-investor-generator.ts
- test/support/generator/random-value-generator.ts
Add the `POST /deals/{dealIdentifier}/investors` endpoint
I've added the endpoint with the following logic:
1. The request body is an array containing an object of the following shape
```
{
"portfolioIdentifier": "E1",
"dealIdentifier": "0020900111",
"lenderType": "500",
"effectiveDate": "2023-03-31",
"expiryDate": "2023-03-31",
"dealStatus": "A",
"currency": "USD",
}
```
where `portfolioIdentifier`, `lenderType`, `expiryDate` and `dealStatus` are optional and have defaults
1. We validate the below, returning a 400 if any rule fails
- `portfolioIdentifier` has length between 0 and 2 if it is present
- `dealIdentifier` exists, has length 10 and begins with either `0020`, `0030` or `0040`
- `lenderType` has length between 0 and 3 if it is present
- `effectiveDate` exists, is a real date, …
> feat(APIM-75): add endpoint to post a deal investor

- README.md
- src/main.module.ts
- src/modules/acbs-authentication/caching-acbs-authentication.service.ts
- test/support/wait-for.ts
In https://github.com/UK-Export-Finance/tfs-api/pull/53, we added caching of the ACBS id token, but didn't document how long the token could be safely cached for. This PR documents this.
I've added this information to the README
> docs(APIM-97): document caching of ACBS id token

- src/modules/acbs/acbs-config-base-url.type.ts
- src/modules/acbs/acbs-deal-guarantee.service.ts
- src/modules/acbs/acbs-deal-party.service.ts
- src/modules/acbs/acbs-deal.service.ts
- src/modules/acbs/acbs-facility-guarantee.service.test.ts
- src/modules/acbs/acbs-facility-guarantee.service.ts
- src/modules/acbs/acbs-facility-party.service.ts
- src/modules/acbs/acbs-party-external-rating.service.ts
- src/modules/acbs/acbs-party.service.ts
- src/modules/acbs/dto/acbs-get-facility-guarantees-response.dto.ts
As part of migrating the `GET /facilities/{facilityId}/guarantees` endpoint, we need to be able to get facility guarantees for a facility from ACBS.
Note this does not _complete_ APIM-122, that will be done by adding an endpoint that uses this service afterwards.
I've created `AcbsFacilityGuaranteeService` in the `acbs` module for doing this.
Unfortunately the GET endpoint we use from ACBS has surprising behaviour:
- (A) if you try to get the guarantees for a facility that doesn't exist, then you get a `200 OK` response where the response body is `null`
- (B) if you try to get the guarantees for a facility that does exist, then you get one of:
1. a `200 OK` response where the response body is an array of guarantees
2. a `200 OK` response where the response body is an empty array 
3. a …
> feat(APIM-122): add acbs service for getting facility guarantees for a facility

- src/modules/acbs/acbs-facility-guarantee.service.test.ts
- src/modules/acbs/acbs-facility-guarantee.service.ts
- src/modules/acbs/acbs-facility-party.service.test.ts
- src/modules/acbs/acbs.module.ts
- src/modules/facility-guarantee/dto/get-facility-guarantees-params.dto.ts
- src/modules/facility-guarantee/dto/get-facility-guarantees-response.dto.ts
- src/modules/facility-guarantee/facility-guarantee.controller.test.ts
- src/modules/facility-guarantee/facility-guarantee.controller.ts
- src/modules/facility-guarantee/facility-guarantee.interface.ts
- src/modules/facility-guarantee/facility-guarantee.module.ts
- src/modules/facility-guarantee/facility-guarantee.service.test.ts
- src/modules/facility-guarantee/facility-guarantee.service.ts
- src/modules/facility-investor/facility-investor.controller.test.ts
- src/modules/facility-investor/facility-investor.service.test.ts
- src/modules/tfs.module.ts
- test/common-tests/request-url-param-validation-api-tests/facility-identifier-url-param-validation-api-tests.ts
- test/deal/get-deal-by-deal-identifier.api-test.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/facility-guarantee/get-facility-guarantees.api-test.ts
- test/facility-investor/post-facility-investor.api-test.ts
- test/support/generator/get-facility-guarantees.generator.ts
- test/support/generator/random-value-generator.ts
The `GET /facility/{facilityIdentifier}/guarantee` endpoint in Mulesoft allows you to get all guarantees for a facility. I have migrated this to `GET /facilities/{facilityIdentifier}/guarantees` in the TFS API
This endpoint:
1. Validates that the specified `facilityIdentifier` has 10 characters and matches `/^00\d{8}$`
2. Gets an id token for ACBS.
3. Uses the id token to `GET /Portfolio/E1/Facility/{facilityIdentifier}/FacilityGuarantee` from ACBS
4. Transforms the response the same way that Mulesoft does:
5. Returns a 200 with the data.
Note that ACBS has strange behaviour for this endpoint, it will return a 200 response with a response body of `null` if the facility does not exist, but it will also do it for some facilities that _do_ exist. Our TFS endpoint will return a 404 in this …
> feat(APIM-122): add endpoint to get guarantees for a facility

- .env.sample
- .github/workflows/development.yml
- docker-compose.yml
- src/config/app.config.test.ts
- src/config/app.config.ts
- src/config/invalid-config.exception.ts
- src/main.module.ts
- test/support/environment-variables.ts
Currently the application logs at info level and above, but there is no way to configure this during development / for each deployment.
I've added an environment variable, LOG_LEVEL, for configuring the log level. `app.config.ts` validates that it is a valid log level to be used.
> feat(APIM-184): control log level with environment variable

- .github/workflows/development.yml
GitHub is generating already used `run_number`, this hinders deployment due to already existing revision name.
* Refer to unique `run_id`, `sha` is an ideal candidate however due to revision name length constraint `github.sha` cannot be used.
> fix(revision): revision suffix to refer to run_id

- .github/workflows/README.md
- .github/workflows/test.yml
- README.md
- jest.config.ts
- package.json
- tsconfig.build.json
Docker build and run processes are not being triggered as part of the CI/CD pipeline.
* Added `e2e-tests` job to the QA workflow, which will trigger docker build and run processes.
* Introduced `.e2e-test.ts` extensions for end-to-end tests with actual requests to ACBS.
* Updated and enhanced documentation pertaining to test QA and TS  compilation.
* Currently `e2e-tests` script is executed with `--passWithNoTests` flag since no `*.e2e-test.ts` exist, once introduced flag should be removed and relevant documentation should be updated.
> feat(APIM-249): CICD E2E execution

- src/modules/acbs-authentication/acbs-authentication.module.ts
- src/modules/acbs/acbs-http.service.ts
- src/modules/acbs/acbs.module.ts
- src/modules/acbs/wrap-acbs-http-error-callback.ts
- src/modules/http/filter-axios-request-for-logging.helper.test.ts
- src/modules/http/filter-axios-request-for-logging.helper.ts
- src/modules/http/filter-axios-response-for-logging.helper.test.ts
- src/modules/http/filter-axios-response-for-logging.helper.ts
- src/modules/http/http-module-options.interface.ts
- src/modules/http/http.module.test.ts
- src/modules/http/http.module.ts
- src/modules/http/log-axios-request.axios-interceptor.test.ts
- src/modules/http/log-axios-request.axios-interceptor.ts
- src/modules/http/log-axios-response-error.axios-interceptor.test.ts
- src/modules/http/log-axios-response-error.axios-interceptor.ts
- src/modules/http/log-axios-response-success.axios-interceptor.test.ts
- src/modules/http/log-axios-response-success.axios-interceptor.ts
- src/modules/http/type/axios-request-interceptor.type.ts
- src/modules/http/type/axios-response-error-interceptor.type.ts
- src/modules/http/type/axios-response-success-interceptor.type.ts
- src/modules/party/party.module.ts
We currently don't log requests to ACBS and responses from ACBS from ACBS unless there is an unexpected exception. Even if there is an unexpected exception, we are currently only logging the request to ACBS, not the response body from it.
We'd like to log requests to/responses from ACBS to help with debugging any issues and with verifying that we are sending the correct PUT / POST requests to ACBS.
I've created a new module, `HttpModule`, that all modules should use _instead of_ the `HttpModule` from `@nestjs/axios`.
This new module can be configured in the same way as `@nestjs/axios`'s `HttpModule`. 
When the new module is registered, it registers and re-exports the `@nestjs/axios` `HttpModule` and `HttpService`.
It also attaches [axios …
> feat(APIM-217): log acbs http requests/responses

- src/constants/enum.constant.ts
- src/constants/enums/guarantee-type-code.ts
- src/constants/enums/income-class-code.ts
- src/modules/acbs/acbs-deal-party.service.ts
- src/modules/acbs/acbs-facility-fixed-fee.service.test.ts
- src/modules/acbs/acbs-facility-fixed-fee.service.ts
- src/modules/acbs/acbs.module.ts
- src/modules/acbs/dto/acbs-get-facility-fixed-fee-response.dto.ts
- src/modules/acbs/known-errors.ts
- src/modules/acbs/wrap-acbs-http-error-callback.ts
- src/modules/facility-fixed-fee/dto/get-facility-fixed-fee-params.dto.ts
- src/modules/facility-fixed-fee/dto/get-facility-fixed-fee-response.dto.ts
- src/modules/facility-fixed-fee/facility-fixed-fee.controller.test.ts
- src/modules/facility-fixed-fee/facility-fixed-fee.controller.ts
- src/modules/facility-fixed-fee/facility-fixed-fee.module.ts
- src/modules/facility-fixed-fee/facility-fixed-fee.service.test.ts
- src/modules/facility-fixed-fee/facility-fixed-fee.service.ts
- src/modules/tfs.module.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/facility-fixed-fee/get-facility-fixed-fees.api-test.ts
- test/support/generator/get-facility-fixed-fee-generator.ts
The GET /facilities/{facilityId}/fixed-feesendpoint allows the client to retrieve all fixed fees for a specific facility. I have migrated the GET ‘/facility/{facilityId}/fixedFee’ endpoint to the TFS API.
This endpoint:
- Validates that the specified facilityIdentifier has 10 characters and matches the regex pattern using the `ValidatedFacilityIdentifierApiProperty` decorator.
- Uses the id token to GET /Portfolio/E1/Facility/{facilityIdentifier}/Fee from ACBS
- Transforms the response the same way that Mulesoft does: Returns a 200 with the data (this includes the case of an empty array if the facility has no fees
- Returns a 200 and an empty array if the facility does not exist (ACBS returns the same response for no fees as facility not existing -- so we can not identify whether the …
> feat: added GET `/facility/{facilityId}/fixedFee` endpoint

- src/modules/facility-investor/dto/create-facility-investor-params.dto.ts
- src/modules/facility-investor/dto/create-facility-investor-request.dto.ts
- src/modules/facility-investor/facility-investor-to-create.interface.ts
- src/modules/facility-investor/facility-investor.controller.test.ts
- src/modules/facility-investor/facility-investor.controller.ts
- src/modules/facility-investor/facility-investor.service.test.ts
- test/common-tests/request-url-param-validation-api-tests/facility-identifier-url-validation-api-tests.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/facility-fixed-fee/get-facility-fixed-fees.api-test.ts
- test/facility-guarantee/get-facility-guarantees.api-test.ts
- test/facility-investor/get-facility-investors-by-facility-identifier.api-test.ts
- test/facility-investor/post-facility-investor.api-test.ts
During testing, the client used the `POST /facilities/{facilityId}/investors` endpoint and received a 400 response with an empty response message.
After investigation, it turned out that this was actually user error - the client had used `:facilityIdentifier` as the facility id in the URL which caused an ACBS 400 error with an empty response message. However it did highlight 2 changes we wanted to make to improve usability and prevent this user error happening again:
1. remove `facilityIdentifier` from the request body since it is already in the URL
2. add the validation rules to `facilityIdentifier` in the URL that we're using on the newer endpoints.
I'll also raise a ticket to make sure the above 2 changes are implemented across _all_ our endpoints.
For `POST …
> feat(APIM-244): validate facility id in post facility investor

- src/modules/acbs/acbs-deal-borrowing-restriction.service.test.ts
- src/modules/acbs/acbs-deal-borrowing-restriction.service.ts
- src/modules/acbs/acbs-deal-party.service.test.ts
- src/modules/acbs/acbs-deal.service.get-deal-by-identifier.test.ts
- src/modules/acbs/acbs-facility-covenant.service.get-covenants.test.ts
- src/modules/acbs/acbs-facility-fixed-fee.service.test.ts
- src/modules/acbs/acbs-facility-loan.service.test.ts
- src/modules/acbs/acbs-facility-party.service.get-by-facility-identifier.test.ts
- src/modules/acbs/acbs.module.ts
- src/modules/acbs/dto/acbs-update-deal-borrowing-restriction-request.dto.ts
- src/modules/deal-guarantee/deal-guarantee.controller.test.ts
- src/modules/deal-investor/deal-investor.controller.test.ts
- src/modules/facility-covenant/facility-covenant.controller.test.ts
- src/modules/facility-fixed-fee/facility-fixed-fee.controller.test.ts
- src/modules/facility-guarantee/facility-guarantee.controller.test.ts
- src/modules/facility-loan/facility-loan.controller.test.ts
- test/support/generator/random-value-generator.ts
For APIM-170, we want to create a borrowing restriction for every deal we create through `POST /deals`. We need to do this through the `PUT /Portfolio/{portfolioId}/Deal/{dealId}/BorrowingRestriction`.
In this PR, we create the ACBS service for sending this request (note that this does not complete APIM-170, but is the first part of it).
I've created `AcbsDealBorrowingRestrictionService` with a method for sending a PUT to `/Portfolio/{portfolioId}/Deal/{dealId}/BorrowingRestriction` that has our usual error handling for ACBS requests.
I added a `portfolioId` method to `RandomValueGenerator` to make it easier to generate a random portfolio id for tests.
> feat(APIM-170): add acbs deal borrowing restriction service

- src/constants/properties.constant.ts
- src/logging/log-keys-to-redact.test.ts
- src/logging/log-keys-to-redact.ts
- src/modules/acbs-adapter/acbs-exception-transform.interceptor.test.ts
- src/modules/deal/deal-borrowing-restriction.service.test.ts
- src/modules/deal/deal-borrowing-restriction.service.ts
- src/modules/deal/deal.controller.test.ts
- src/modules/deal/deal.module.ts
- src/modules/deal/deal.service.create-deal.test.ts
- src/modules/deal/deal.service.get-deal-by-identifier.test.ts
- src/modules/deal/deal.service.ts
- test/deal/post-deal.api-test.ts
- test/support/generator/create-deal-generator.ts
After creating a deal, we need to update a borrowing restriction for the deal using the `PUT /Portfolio/{portfolioId}/Deal/{dealId}/BorrowingRestriction` endpoint in ACBS.
All fields for the request are set from constants.
The ACBS service for sending the PUT request was created in an earlier PR.
In this PR, I've created a `DealBorrowingRestrictionService` that uses the `AcbsDealBorrowingRestrictionService` to update the deal borrowing restriction.
This service will translate any `AcbsResourceNotFoundException` or `AcbsBadRequestException` from `AcbsDealBorrowingRestrictionService` into a 500 error, since these errors would **not** be caused by the client but by something going wrong on the server's side or ACBS's side.
Note that this endpoint leaves the possibility for a deal to be …
> feat(APIM-170): update deal borrowing restriction after creating deal

- src/modules/acbs/acbs-bundle-information.service.ts
- src/modules/acbs/acbs-facility-covenant.service.ts
- src/modules/acbs/acbs-facility-fixed-fee.service.ts
- src/modules/acbs/acbs-facility-guarantee.service.create-guarantee.test.ts
- src/modules/acbs/acbs-facility-guarantee.service.get-guarantees.test.ts
- src/modules/acbs/acbs-facility-guarantee.service.replace-guarantee.test.ts
- src/modules/acbs/acbs-facility-guarantee.service.ts
- src/modules/acbs/acbs-facility-loan.service.ts
- src/modules/acbs/dto/acbs-create-facility-guarantee.dto.ts
- src/modules/acbs/dto/acbs-get-facility-guarantees-response.dto.ts
- src/modules/acbs/dto/acbs-update-facility-guarantee-request.dto.ts
- src/modules/acbs/dto/base-entities/acbs-base-facility-guarantee.interface.ts
As part of APIM-123, we need to be able to send PUT requests to ACBS to update facility guarantees.
(Note: this PR is only part of APIM-123 and does not complete it).
I've expanded the AcbsFacilityGuaranteeService to have a method for sending a PUT request to `/Portfolio/{portfolioId}/Facility/{facilityId}/FacilityGuarantee` in ACBS.
If ACBS responds with a 400 that says "The facility not found or the user does not have access" then the service throws an `AcbsResourceNotFoundException`. Any other 400 will result in an `AcbsBadRequestException`, and any unexpected error results in an `AcbsUnexpectedException`.
- I noticed that some of our ACBS services didn't have the `@Injectable` decorator so I added them.
- I've commonised the interfaces for the different ACBS Facility Guarantee …
> feat(APIM-123): expand acbs service to put facility guarantee

- src/modules/acbs/acbs-facility-guarantee.service.get-guarantees.test.ts
- src/modules/acbs/dto/acbs-get-facility-guarantees-response.dto.ts
- src/modules/facility-covenant/facility-covenant.controller.test.ts
- src/modules/facility-covenant/facility-covenant.service.ts
- src/modules/facility-covenant/facility-covenant.service.update-covenants.test.ts
- src/modules/facility-guarantee/dto/create-facility-guarantee-response.dto.ts
- src/modules/facility-guarantee/dto/facility-guarantees-params.dto.ts
- src/modules/facility-guarantee/dto/update-facility-guarantees-request.dto.ts
- src/modules/facility-guarantee/facility-guarantee.controller.create-guarantee.test.ts
- src/modules/facility-guarantee/facility-guarantee.controller.get-guarantees.test.ts
- src/modules/facility-guarantee/facility-guarantee.controller.ts
- src/modules/facility-guarantee/facility-guarantee.controller.update-guarantees.test.ts
- src/modules/facility-guarantee/facility-guarantee.service.create-guarantee.test.ts
- src/modules/facility-guarantee/facility-guarantee.service.get-guarantees.test.ts
- src/modules/facility-guarantee/facility-guarantee.service.ts
- src/modules/facility-guarantee/facility-guarantee.service.update-guarantees.test.ts
- test/common-tests/request-field-validation-api-tests/non-empty-object-request-validation-api-tests.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/facility-covenant/patch-facility-covenants.api-test.ts
- test/facility-guarantee/patch-facility-guarantees.api-test.ts
- test/support/generator/get-facility-guarantee-generator.ts
The `PATCH /facility/{facilityId}/guarantee` endpoint in Mulesoft allows the client to edit the expiration date and/or guaranteed limit of all the guarantees of a facility.
I've migrated that to `PATCH /facilities/{facilityId}/guarantees` in TFS. This:
1. validates that the request body is not an empty object (and is an object)
2. validates the optional fields `guaranteedLimit` and `expirationDate`
3. gets all guarantees for the facility from ACBS
- We throw a 404 error if ACBS returns a `200 null` response. This happens if the facility doesn't exist, but a limitation in ACBS means this also sometimes happens if the facility _does_ exist.
4. for each guarantee, sends a PUT request to `/Portfolio/{portfolioId}/Facility/{facilityId}/FacilityGuarantee` to update the guarantee with the new …
> feat(APIM-123):  add endpoint to patch facility guarantees

- src/modules/acbs/dto/acbs-create-bundle-information-request.dto.ts
- src/modules/acbs/dto/acbs-get-bundle-information-response.dto.ts
In a previous ticket, we left a TODO for APIM-311 (a future ticket to deal with a field in ACBS being deprecated at the end of 2024). It's looking unlikely that we'll do this ticket anytime soon (if at all), so I don't think it's worth keeping the TODOs in the code. When we do APIM-311, we can just search for `InitialBundleStatusCode` anyway
I've removed the 2 TODOs
> refactor: remove todos for APIM-311

- src/modules/facility-loan-transaction/dto/get-facility-loan-transaction-response.dto.ts
- src/modules/facility-loan-transaction/facility-loan-transaction.service.get-loan-transaction-by-bundle-id.test.ts
- test/facility-loan-transaction/get-facility-loan-transaction.api-test.ts
As part of the bug fix [APIM-364](https://ukef-dtfs.atlassian.net/browse/APIM-364), we added behaviour that handles when accrual/repayment schedules are missing. This PR adds API and unit tests to test this new behaviour.
I added test cases for:
1. No accrual schedules with category code `PAC01`
2. No accrual schedules with category code `CTL01`
3. No accrual schedules of any kind
4. No repayment schedules
> feat(APIM-364): add tests to check we handle missing GET loan transaction fields correctly

- src/modules/date/date-string.transformations.test.ts
- src/modules/date/date-string.transformations.ts
- src/modules/deal/deal.service.create-deal.test.ts
- test/deal/post-deal.api-test.ts
- test/support/generator/create-deal-generator.ts
In the POST deals endpoint, we construct the Description field that we send to ACBS by appending various fields from the request to our API, including a string representation of the effectiveDate (the earliest date out of today and the guaranteeCommencementDate provided in the API request). In TFS, this was in DD/MM/YYYY format, but in the Mulesoft API, it is in DD/MM/YY format.
I changed the TFS implementation to use DD/MM/YY format so as to match Mulesoft, and updated the tests to reflect this.
> feat(APIM-449): fix incorrect date format in description field for post deals endpoint

- src/modules/facility-loan-transaction/facility-loan-transaction.service.get-loan-transaction-by-bundle-id.test.ts
- src/modules/facility-loan-transaction/facility-loan-transaction.service.ts
- test/facility-loan-transaction/get-facility-loan-transaction.api-test.ts
- test/support/generator/get-facility-loan-transaction-generator.ts
In the `GET /facilities/{facilityId}/loan-transactions/{bundleId}` endpoint the `indexRateChangeFrequency` value is taken from the pac accrual schedule. This is never set in the POST request so will always be null. 
`indexRateChangeFrequency` is only set in the Contractual Interest, non Risk Free Rate accrual schedules (when Product Group = EWCS and Currency = USD). So the ctl accrual schedule is used to set the `indexRateCHangeFrequency` value instead.
> feat(apim-453): Make `indexRateChangeFrequency` useful in `GET /facilities/{facilityId}/loan-transactions/{bundleId}`

- src/constants/properties.constant.ts
- src/modules/facility-loan/accrual-schedule.builder.ts
- test/support/generator/create-facility-loan-generator.ts
In MuleSoft int RFR accrual schedules have `RateSetLeadDays` set to a constant value `0` in the ACBS request body, this is not set currently, although defaults to `0`.
For consistency `RateSetLeadDays` has been set to the constant value for int RFR accrual schedules.
The test generator has been updated.
> fix(apim-455): Update POST /facilities/:facilityIdentifier/loans ACBS request with RateSetLeadDays when required

- src/constants/enums/income-class-code.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
Noticed that Fixed Fee creation doesn't work for EWCS facilities.
Simple typo fix. Confirmed in ACBS reference list.
> fix: typo in incomeClass enum

- src/constants/properties.constant.ts
- src/decorators/parse-required-and-nullable-validation.helper.ts
- src/decorators/validated-boolean-api-property.decorator.ts
- src/decorators/validated-date-only-api-property.decorator.ts
- src/decorators/validated-number-api-property.decorator.ts
- src/decorators/validated-string-api-property.decorator.ts
- src/modules/acbs/dto/bundle-actions/new-loan-request.bundle-action.ts
- src/modules/deal-guarantee/deal-guarantee.controller.test.ts
- src/modules/deal-guarantee/deal-guarantee.service.create-guarantee.test.ts
- src/modules/deal-guarantee/deal-guarantee.service.ts
- src/modules/deal-guarantee/dto/create-deal-guarantee-request.dto.ts
- src/modules/facility-covenant/dto/update-facility-covenants-request.dto.ts
- src/modules/facility-fixed-fee/dto/create-facility-fixed-fee-request.dto.ts
- src/modules/facility-guarantee/dto/update-facility-guarantees-request.dto.ts
- src/modules/facility-loan/dto/create-facility-loan-request.dto.ts
- src/modules/facility-loan/facility-loan.service.ts
- src/modules/facility/dto/base-facility-request.dto.ts
- test/common-tests/request-field-validation-api-tests/base-facility-fields-validation-api-tests.ts
- test/common-tests/request-field-validation-api-tests/boolean-field-validation-api-tests.ts
- test/common-tests/request-field-validation-api-tests/enum-field-validation-api-tests.ts
- test/common-tests/request-field-validation-api-tests/non-negative-number-field-validation-api-tests.ts
- test/common-tests/request-field-validation-api-tests/number-field-validation-api-tests.ts
- test/common-tests/request-field-validation-api-tests/string-field-validation-api-tests.ts
- test/deal-guarantee/post-deal-guarantee.api-test.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/facility-fixed-fee/post-facility-fixed-fees.api-test.ts
- test/facility-loan/post-facility-loan.api-test.ts
- test/facility/put-facility-by-facility-identifier.api-test.ts
- test/facility/put-facility-by-facility-identifier.test-parts/issue-facility-api-tests.ts
- test/support/generator/create-facility-loan-generator.ts
In testing for APIM-369, we found a few small differences between TFS (Node) and TF-EA (Mule) that are not urgent but would be good to resolve.
- removed `guaranteeTypeCode` from POST /deals/{dealId}/guarantees request as it has only 1 allowed value
- removed null values for CashEventList that were being set by POST /facilities/{facilityId}/loans
- made `indexRateChangeFrequency` required for EWCS loans in POST /facilities/{facilityId}/loans
- made `issueDate` required when `facilityStageCode` is 07 for POST /facilities and PUT /facilities/{facilityId}
- made `capitalConversionCode` required for GEF facilities for POST /facilities and PUT /facilities/{facilityId}
> fix(APIM-369): fix minor differences compared to TF-EA

- src/modules/acbs/dto/acbs-base-facility-request.dto.ts
- src/modules/facility/facility.service.ts
- test/support/generator/create-facility-generator.ts
- test/support/generator/update-facility-generator.ts
After last ACBS update field FacilityOverallStatus is not accepted anymore for Facility creation and update.
Remove field FacilityOverallStatus.
- This might be temporary change. 
- We need to be careful releasing this to Production, field FacilityOverallStatus might be required in Production.
> fix(APIM-492): remove field FacilityOverallStatus from Facility POST and PUT

- src/helpers/regex.helper.ts
nestjs/swagger decorator `apiProperty` takes a string for `pattern`, and not a Regexp. As a result, we turn our existing regexp into strings to be used in swagger.
In the old implementation of this, regex expressions were getting split prematurely if there was an additional `/` in the expression. 
I've created a helper function to avoid this occurring, as apposed to relying on `split`
> fix(APIM-531): fix swagger regex field

- src/config/acbs-authentication.config.ts
- src/config/acbs.config.test.ts
- src/config/acbs.config.ts
- src/config/app.config.test.ts
- src/config/app.config.ts
- src/config/mdm.config.ts
- src/helpers/get-int-config.helper.test.ts
- src/helpers/get-int-config.ts
- test/common-tests/environment-variable-parsing-unit-tests.ts
Current way to parse environment variables and set default value doesn't allow using 0. 0 can be useful for ACBS_MAX_REDIRECTS , ACBS_TIMEOUT and similar integer environment variables.
Created helper `getIntConfig`. It parses input string and returns integer from input or optional default value.
Helper throws exception for these edge cases:
- input is set, but not string
- input and default values are undefined
- input is not integer in string format. For example it is float or has some non digital characters
- input number is not using decimal base
Moved boolean environment variable test to shared test `withEnvironmentVariableParsingUnitTests`
> feat(APIM-468): Allow numeric environment variables to be set to 0

- src/modules/acbs/dto/acbs-base-facility-request.dto.ts
- src/modules/facility/facility.service.ts
- test/support/generator/create-facility-generator.ts
- test/support/generator/update-facility-generator.ts
We implemented APIM-492 to resolve an issue in the ACBS test environment. That issue was that we were unable to create facilities because ACBS's validation on the FacilityOverallStatus field was incorrect. We were able to resolve this by removing the field from our facility creation request as it is not used anyway.
We were aware that the FacilityOverallStatus field had been included in facility creation requests from Mulesoft because the Mulesoft dev team had found that it was required by ACBS. It was no longer required in the ACBS test environment, but at the time of implementing APIM-492 we were unsure if it was required or not in the ACBS production environment (which was 1 patch behind the ACBS test environment).
We now know that the FacilityOverallStatus field is not required in the …
> chore: remove redundant TODOs from APIM-492

- src/interceptors/warning-errors-header.interceptor.test.ts
I noticed that the `WarningErrorsInterceptor` was missing unit tests.
I added some unit tests to the `WarningErrorsInterceptor`
> refactor(APIM-308): add unit tests for WarningErrorsInterceptor

- src/logging/logging-interceptor.helper.test.ts
We have unit tests for other Interceptors, LoggingInterceptor is very simple, but Unit test might be useful.
Simple unit test for LoggingInterceptor.
The way how exceptions behaves in tests, matches real execution in Interceptors and controller.
It would be nice to have e2e test for logging
> chore(APIM-318): added unit test for LoggingInterceptor

- .github/workflows/publish.yml
Reverted back to `release-please` GitHub Actions plugin instead of `release-please` CLI command.
> fix(release-please): updated to github plugin

- src/constants/examples/gift.examples.constant.ts
- src/constants/gift.constant.ts
- src/modules/gift/dto/facility.ts
- test/docs/__snapshots__/get-docs-yaml.api-test.ts.snap
- test/gift/assertions/index.ts
- test/gift/assertions/number-string-validation.ts
- test/gift/create-facility-validation.api-test.ts
This PR updates the facility creation (overview) validation to enforce the length of the `obligorUrn` field.
- Update `VALIDATION` constants.
- Update `GiftFacilityDto`.
- Add DRY test assertion function, `numberStringValidation`.
- Update API tests.
> feat(GIFT-10828): create a facility - obligorUrn validation

- src/constants/gift.constant.ts
- src/modules/gift/dto/facility-creation.ts
- test/gift/assertions/array-of-nested-objects-number-validation.ts
- test/gift/assertions/array-of-nested-objects-string-validation.ts
- test/gift/assertions/array-of-objects-number-validation.ts
- test/gift/assertions/array-of-objects-string-validation.ts
- test/gift/assertions/generate-payload.ts
- test/gift/assertions/index.ts
- test/gift/assertions/response-assertion.ts
- test/gift/create-facility-validation-repayment-profiles.api-test.ts
- test/gift/create-facility-validation.api-test.ts
This PR improves API test coverage for the repayment profiles aspect of the "create facility" endpoint.
- Update `REPAYMENT_PROFILE.NAME` to have a minimum length of 1, instead of 0.
- Create new DRY test assertions:
- `arrayOfNestedObjectsNumberValidation`
- `arrayOfNestedObjectsStringValidation`
- Update `generatePayloadArrayOfObjects` to consume a `grandParentFieldName` param and return a nested array of objects with a provided field/value.
- Add API tests for repayment profiles.
- Add a missing `type` property.
- Improve `arrayOfObjectsNumberValidation` and `arrayOfObjectsStringValidation`  payload constructions.
- Update `assert400Response` to use `HttpStatus`.
- API test coverage improvements
> chore(GIFT-10023): create a facility - repayment profiles - api tests

- src/modules/gift/gift.currency.controller.ts
The GIFT currency controller has an invalid Open API property. This causes deployment to fail.
- Remove invalid Open API property.
> chore(GIFT-12084): remove invalid open api field

- src/modules/gift/gift.http.service.test.ts
- src/modules/gift/gift.http.service.ts
- test/gift/create-facility-approve-status-error-handling.api-test.ts
- test/gift/create-facility-counterparty-error-handling.api-test.ts
- test/gift/create-facility-creation-error-handling.api-test.ts
- test/gift/create-facility-fixed-fee-error-handling.api-test.ts
- test/gift/create-facility-obligation-error-handling.api-test.ts
- test/gift/create-facility-repayment-profile-error-handling.api-test.ts
- test/gift/get-currency-supported.api-test.ts
- test/gift/get-fee-type-supported.api-test.ts
- test/gift/test-helpers/index.ts
- test/support/interfaces/mock-gift-response.interface.ts
This PR updates the GIFT integration to handle 403/Forbidden responses from GIFT.
As part of this PR, have also updated the API tests to have DRY mock endpoint responses,
- Update `GIFT_API_ACCEPTABLE_STATUSES` to include `HttpStatus.FORBIDDEN`.
- Update all API tests to include 403/Forbidden assertions.
- Update appropriate API tests to have a DRY `setupMocks` function.
- Update test helpers to create mock responses with a new `MockGiftResponse` interface.
> chore(GIFT-12306): handle forbidden statuses, dry mock responses

- src/modules/gift/dto/request/counterparty.ts
- src/modules/gift/helpers/generate-counterparty-share-percentage-errors/index.test.ts
- src/modules/gift/helpers/generate-counterparty-share-percentage-errors/index.ts
- test/gift/assertions/array-of-objects-share-percentage-validation.ts
- test/gift/create-facility-validation-counterparties-share-percentage.api-test.ts
Counterparty `sharePercentage` validation has been recently updated and no longer handled some validation scenarios correctly.
- Update counterparty request DTO.
- Update `generateCounterpartySharePercentageErrors` to check for MIN/MAX.
- Update API tests.
List any additional fixes or improvements.
<details>
<summary>Show/hide</summary>
```json
```
</details>
<details>
<summary>Show/hide</summary>
Add screenshots here.
</details>
> fix(GIFT-13101): counterparty sharePercentage validation

- .github/actions/acr/action.yml
- .github/actions/notify/action.yml
- .github/workflows/deployment.yml
- .github/workflows/github.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/purge.yml
- .github/workflows/sca.yml
- .github/workflows/test.yml
Update GitHub actions checkout plugin to latest version.
* Updated to `actions/checkout@v5`.
> chore(github-actions): actions/checkout@v5

- .markdownlint.json
- .prettierrc.json
- README.md
Markdown linting's max length was too short.
- Update `.markdownlint.json`.
- Update `.prettierrc`.
- Update `README.md`.
- Minor `README.md` alignment.
<details>
<summary>Show/hide</summary>
```json
```
</details>
<details>
<summary>Show/hide</summary>
Add screenshots here.
</details>
> chore(APIM-618): update markdown linting max length to 160

- package.json
`.md` and `.yml` validation was running in commit hooks even if no such files were staged.
- Update `package.json`.
List any additional fixes or improvements.
<details>
<summary>Show/hide</summary>
```json
```
</details>
<details>
<summary>Show/hide</summary>
Add screenshots here.
</details>
> chore(APIM-618): only run commit hooks on staged files
